### PR TITLE
feat: change error mark styling to yellow

### LINKED ISSUE #12: Error underline in online editor difficult to see for those with colourblindness
Hello,

I am red-green colourblind, and finding the red dashed underline that indicates an error in the online editor is quite difficult. A different colour, such as a bright yellow, would be much easier to spot; alternatively, a thicker line or brighter shade would also be an improvement in terms of accessibility.

### PR DESCRIPTION
**Pull request by LeoDog896**
Proposal that may close #12.

### CODE REVIEW

**Comment by huacnlee** [comment]
Which is new style？

**Comment by LeoDog896** [comment]
The new style is the bolder one:
image

**Comment by Jamalam360** [comment]
Does this repo do deployment previews?

**Comment by LeoDog896** [comment]
No deployment previews - GitHub pages is planning to add some sort of functionality for it, but otherwise we aren't integrated with vercel or netlify.

**Comment by Jamalam360** [comment]
Ok, I'll run this branch locally when I get home so I can see

**Comment by nathanielknight** [comment]
This LGTM, but I think we might need a higher contrast colour as well as the bold style to really fix #12.

I tried this locally with filters to simulate different kinds of colourblindness and it was still challenging to pick out the error marks.

**Comment by nathanielknight** [comment]
For comparison, 

Original:
image

New:
image

**Comment by nathanielknight** [comment]
Another option: keep the dotted styling but change the colour to something like #E8C83A:

image

This has a much better [contrast score](https://coolors.co/contrast-checker/e8c83a-253451).

**Comment by LeoDog896** [comment]
> Yes, I don't think a red is the right option here, or if so (for semantic reasons of red == error) we need to change it quite drastically to get proper contrast

Yeah, the only reason why I chose red _was_ to indicate an error (Jakob's Law) but I don't think compromising accessibility for a silly issue like that is a good idea :+1:. I'll change it to yellow, then.

**Review by huacnlee — APPROVED** [review]

**Review by nathanielknight — APPROVED** [review]

**Comment by LeoDog896** [comment]
*just to be clear, are the reviews for the current change, changing the current one to yellow, or changing the old one to yellow? :sweat_smile:

**Comment by Jamalam360** [comment]
~~yes.~~

**Comment by tomtau** [comment]
changing the old one to yellow?

**Comment by LeoDog896** [comment]
Sounds good!

**Comment by Jamalam360** [comment]
@LeoDog896 can we get another screenshot please?

**Comment by LeoDog896** [comment]
image

**Pull request merged**
