### PR TITLE
Port to wasm_bindgen, web-sys.

### LINKED ISSUE #13: migrate from stdweb to wasm-bindgen and websys
[stdweb crate that is no longer maintained](https://rustsec.org/advisories/RUSTSEC-2020-0056.html)

### PR DESCRIPTION
**Pull request by birkenfeld**
Fixes #13

Announcement caught my eye, and I wanted to play around with `wasm-pack` anyway, so I tried my hand here.

Since I'm new at it, I might be doing stupid things.

To test I used `wasm-pack --target web` and copied the `pkg/*` files together with `static/*` into the document root.

PS: I didn't touch the `static mut`s, but I hope there is a better way...

### CODE REVIEW

**Review by tomtau — APPROVED** [review]
awesome work @birkenfeld ! from a quick look, the changes seem all right, I'll try to build it this weekend and see if it works as expected.
BTW could you also bump pest crates to 2.5? I extracted out this exact duplicate code into a helper function in pest_meta: https://github.com/pest-parser/site/blob/7c6edd371a3489886a0ebadf57261a9e5fe09d25/src/lib.rs#L135

See [pest_meta](https://docs.rs/pest_meta/latest/pest_meta/index.html)::[parser](https://docs.rs/pest_meta/latest/pest_meta/parser/index.html)::[rename_meta_rule](https://docs.rs/pest_meta/latest/pest_meta/parser/fn.rename_meta_rule.html#) ... so that line could be rewritten as `error.renamed_rules(rename_meta_rule)`

**Comment by birkenfeld** [comment]
Done! I also read more about the `forget()` calls for closures, which leaks, so I changed the implementation of `add_rules_to_select` to not generate a new `select` but reuse the old one. This way, the event handlers are only set up once. Further, the `set_timeout` can take a `FnOnce` which apparently doesn't need `forget`.

**Comment by birkenfeld** [comment]
Yes, and I see the reason - fix incoming.

**Comment by tomtau** [comment]
@birkenfeld thanks a lot, it seems to work as before now!
I managed to reproduce this older issue: https://github.com/pest-parser/pest/issues/603
The error was a bit different:
```
[Error] RuntimeError: Unreachable code should not be executed (evaluating 'wasm._dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__he88a88ba023a2b44(arg0, arg1)')
	<?>.wasm-function[268] (pest_site.js:168:133)
	<?>.wasm-function[323]
	<?>.wasm-function[50]
	<?>.wasm-function[143]
	<?>.wasm-function[277]
	<?>.wasm-function[357]
	wasm-stub
	__wbg_adapter_25 (pest_site.js:168:133)
	real (pest_site.js:153)
```
Anyway, that issue was in the old version as well, so no need to fix it in this PR (it may also be something to fix in `pest_vm` or elsewhere), unless you have a hunch of what may be causing it.

**Comment by tomtau** [comment]
it seems it's not an issue in `pest_vm`... at least it didn't kill the debugger, it just reported an error (as that syntax is from the older pest version):
```
> g kotlin.pest
Error: Grammar error: error parsing "kotlin.pest"

  --> 27:7
   |
27 |     ( ! [\n] ~ ANY )+ ~  NL*
   |         ^---
   |
   = expected `(`, `&`, `!`, PUSH, peek_slice, identifier, `^`, `"`, or `'`
```

**Comment by birkenfeld** [comment]
Strange, I got a much clearer error - the "no VM" `expect_throw` panic, both with FF and Chrome. Pushed a fix for that now.

The bigger problem is that it is basically impossible to see that (a) there is a problem in the grammar and (b) where it is, since the red lint marking is slight and hard to see on the dark background.

**Comment by tomtau** [comment]
@birkenfeld I got it on Safari, but when I tried again, it showed "no VM"... but yes, I think the current error marking is hard to see: https://github.com/pest-parser/site/issues/12

**Pull request merged**
